# Basic
title: 塔星科技
subtitle: 让天下没有难管的系统
welcome_message: <a href="/">塔星科技</a>
description: 致力于系统运维管理
creator: <a href="/">@takeseem</a>

url: "/"

permalink: /:year/:month/:day/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进去看看

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 进去看看, url: 'https://github.com/takeseem-com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: takeseem
    # duoshuo: 
    
# Social
social:
    weibo: takeseem
    github: takeseem
    twitter: takeseem2099
    gplus: 112827489695545853074
    mail: takeseem@gmail.com

# Google Analytics
ga:
    id: UA-104231311-1
    host: www.takeseem.com
